CREATE TABLE properties (
	ad_title VARCHAR,
	state VARCHAR,
	city VARCHAR,
	neighborhood VARCHAR,
	avenue VARCHAR,
	property_type VARCHAR,
	operation_type VARCHAR,
	physical_condition VARCHAR,
	price INT,
	price_per_m2 INT,
	currency VARCHAR,
	bedrooms_number INT,
	bathrooms_number INT,
	size INT,
	size_unit VARCHAR,
	permalink VARCHAR,
	thumbnail VARCHAR,
	seller_agency VARCHAR,
	latitude VARCHAR,
	longitude VARCHAR,
	ad_id VARCHAR,
	updated_at DATE,
	source_of_info VARCHAR
);